[general]
import = [
	"~/.config/alacritty/theme.toml"
]

[window]
decorations = "None"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 16

[mouse]
hide_when_typing = true

