[colors.normal]
black = '#000000'
red = '#800000'
green = '#008000'
yellow = '#808000'
blue = '#000080'
magenta = '#800080'
cyan = '#008080'
white = '#c0c0c0'

[colors.bright]
black = '#808080'
red = '#ff0000'
green = '#00ff00'
yellow = '#ffff00'
blue = '#0000ff'
magenta = '#ff00ff'
cyan = '#00ffff'
white = '#ffffff'

[colors.primary]
foreground = '#ffffff'
background = '#000000'
